nav:
  title: Blog
  items:
    Archives: /archives
    About: /about
rss: /atom.xml

footer:
  Blog:
    Blog: /
    Archives: /archives
    About: /about
  Projects:
    Transmister: https://github.com/transmister
    Theme Cupertino: https://github.com/MrWillCom/hexo-theme-cupertino
    GitHub Dark Mode: https://github.com/MrWillCom/github-dark-mode
  Me:
    GitHub: https://github.com/MrWillCom
    Patreon: https://www.patreon.com/MrWillCom
    Email: mailto:mr.will.com@outlook.com
