# REMEMBER TO EDIT THIS BEFORE DEPLOY!!!

# the path to your blog's icon:
favicon: /favicon.png

# navigation config
nav:
  # the title displays in the upper left corner which won't change
  title: Blog
  # the items displays in the upper right corner
  items:
    # these items will display as a link
    Archives: /archives
    Projects: /projects
    About: /about
    # these will be automatically be an icon
    GitHub: https://github.com/MrWillCom
    Patreon: https://www.patreon.com/MrWillCom
    CodePen: https://codepen.io/mrwillcom

# footer items
footer:
  # the title
  Blog:
    # the items after the title, display as links
    Blog: /
    Archives: /archives
    Projects: /projects
    About: /about
    RSS: /atom.xml
  # also the title
  Projects:
    # the items
    Transmister: https://github.com/transmister
    CSS&JS Windows UWP XAML Controls: https://github.com/MrWillCom/css-and-js-windows-uwp-xaml-controls
    Theme Cupertino: https://github.com/MrWillCom/hexo-theme-cupertino
    GitHub Dark Mode: https://github.com/MrWillCom/github-dark-mode
  # the title
  Me:
    # items
    GitHub: https://github.com/MrWillCom
    Patreon: https://www.patreon.com/MrWillCom
    CodePen: https://codepen.io/mrwillcom
    Email: mailto:mr.will.com@outlook.com

# the license your posts under
license: CC BY-NC 4.0
# the link of your license
license_link: https://creativecommons.org/licenses/by-nc/4.0

# REMEMBER TO EDIT THIS BEFORE DEPLOY!!!